### ISSUE TITLE
How to get real stop loss

### ISSUE THREAD

**Issue by QingqiLei** [TradeLocker/tradelocker-python#1]
Hi TradeLocker

I used get_all_positions(), and got stopLossId. But stopLossId is a number like 7349874591873869933.
How can I get the real stop loss?

**Comment by ivosluganovic** [comment]
The number that you see is an orderId of an stopLoss order. You should be able to find these details if you query the /trade/accounts/{accountId}/ordersHistory route and find the given orderId.
