### ISSUE TITLE
is there ?

### ISSUE THREAD

**Issue by rjngh2005** [TradeLocker/tradelocker-python#4]
My code in earlier issue is working fine

the login requires the following

"https://demo.tradelocker.com", 
username = "<email>", password = "<pwd>", server = "KOT-DEMO"

can we enter account number ?

**Comment by rjngh2005** [comment]
i found it - 
i have to add the following 
account_id=<xxxx>  
You have to give the integer value of the account number
we dont have to sorround the number with single quotes / double quotes

Is there a documentation information - is there a help file / published by trade locker ?

**Comment by duanebc** [comment]
You can view here.

https://github.com/TradeLocker/tradelocker-python/blob/main/src/tradelocker/tradelocker_api.py#L79-L90

As the function signature suggests int, they're required as int, but optional.  The debugger does query all accounts it seems if one is not specified.

**Comment by ivosluganovic** [comment]
Yes, you can specify the accNum as well.
The accountId and accNum should be specified with most REST calls, but if you only have a single account with your credentials, then it is not required to specify the accNum -- the library will infer it for you.
