### ISSUE TITLE
Error with get_latest_asking_price

### ISSUE THREAD

**Issue by duanebc** [TradeLocker/tradelocker-python#7]
`
from tradelocker import TLAPI
from creds import creds

cred = creds[0]
del cred['cred_id']

tl = TLAPI(environment = "https://demo.tradelocker.com", username = cred['email'], password = cred['password'], server = cred['server'])
symbol_name = 'BTCUSD'
instrument_id = tl.get_instrument_id_from_symbol_name(symbol_name)
print(f"instrument_id: {instrument_id}")
print("\n\n\n\n\n")
price = tl.get_latest_asking_price(instrument_id)
`

$ python tradelocker_testing.py 
 
[INFO] tradelocker.tradelocker_api 2024-04-26 12:24:22,885 tradelocker_api _auth_with_password: 662 Successfully fetched 
authentication tokens
INFO:tradelocker.tradelocker_api:Successfully fetched authentication tokens
 
[DEBUG] tradelocker.tradelocker_api 2024-04-26 12:24:24,125 tradelocker_api _set_account_id_and_acc_num: 216 Neither account_id nor acc_num specified, using the first account
DEBUG:tradelocker.tradelocker_api:Neither account_id nor acc_num specified, using the first account
 
[DEBUG] tradelocker.tradelocker_api 2024-04-26 12:24:24,126 tradelocker_api _set_account_id_and_acc_num: 224 Logging in using the first account, account_id: 276587, acc_num: 1
DEBUG:tradelocker.tradelocker_api:Logging in using the first account, account_id: 276587, acc_num: 1
instrument_id: 206

ERROR:root:Key d (['d']) missing from JSON data {'s': 'no_data'}
Traceback (most recent call last):
  File "C:\Users\duane\code\python\tradelocker\tradelocker_testing.py", line 23, in <module>
    price = tl.get_latest_asking_price(instrument_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duane\code\python\Lib\site-packages\tradelocker\utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duane\code\python\Lib\site-packages\tradelocker\tradelocker_api.py", line 1078, in get_latest_asking_price
    dict[str, float], self.get_quotes(instrument_id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duane\code\python\Lib\site-packages\tradelocker\utils.py", line 115, in wrapper
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duane\code\python\Lib\site-packages\tradelocker\tradelocker_api.py", line 1104, in get_quotes
    latest_price: QuotesType = get_nested_key(response_json, ["d"], QuotesType)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\duane\code\python\Lib\site-packages\tradelocker\utils.py", line 159, in get_nested_key
    raise KeyError(
KeyError: "Key d (['d']) missing from JSON data {'s': 'no_data'}"
(python)

**Comment by ivosluganovic** [comment]
There was an issue with the service, which should now be resolved. Please reopen if you see this again.
